; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:EmbeddedOS]


;platform = espressif32@5.2.0
platform = espressif32

;board = m5stack-core2
board = esp32s3-devkitc-custom
framework = arduino
lib_deps = 
	moononournation/GFX Library for Arduino@^1.6.3
	bblanchon/ArduinoJson@^7.2.1
	;m5stack/M5Core2@^0.2.0
upload_speed = 921600
monitor_speed = 115200
build_flags = 
	-DVSPI=SPI
	-DBOARD_HAS_PSRAM=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DWAVESHARE_OLED_SMARTWATCH
	-DUSE_SMARTWATCH_OS_ICONS
	;-DM5STACK_CORE2
